# Generated by Django 3.2.3 on 2022-11-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasDisponibles',
            fields=[
                ('idCategoria', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rutCliente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=75)),
                ('fechaNacimiento', models.DateField()),
                ('nick', models.CharField(max_length=75)),
                ('clave', models.CharField(max_length=75)),
                ('tipoVehiculo', models.CharField(max_length=75)),
                ('patente', models.CharField(max_length=75)),
                ('modelo', models.CharField(max_length=75)),
                ('marca', models.CharField(max_length=75)),
                ('anno', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('rutRepresentante', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=75)),
                ('clave', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosDisponibles',
            fields=[
                ('idServicios', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreServicio', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('rutTaller', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=75)),
                ('pagina', models.CharField(blank=True, max_length=50, null=True)),
                ('rutRepresentante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoTalleres.representantes')),
            ],
        ),
        migrations.CreateModel(
            name='listadoPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=25)),
                ('idServicios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoTalleres.serviciosdisponibles')),
                ('rutTaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoTalleres.talleres')),
            ],
        ),
        migrations.CreateModel(
            name='listadoCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoTalleres.representantes')),
                ('rutTaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoTalleres.talleres')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('evaluacion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('rutCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoTalleres.clientes')),
                ('rutTaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoTalleres.talleres')),
            ],
        ),
    ]
