# Generated by Django 4.1.1 on 2022-12-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoTalleres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(default='-', max_length=100)),
                ('accion', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acumulado', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('promedio', models.FloatField(default=0)),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoTalleres.talleres')),
            ],
        ),
    ]
