# Generated by Django 4.1.1 on 2022-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoTalleres', '0002_fecharegistro_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
    ]
