# Generated by Django 4.1.1 on 2022-12-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoTalleres', '0002_fecharegistro_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecharegistro',
            name='tipo',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='fecharegistro',
            name='rut',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
