# Generated by Django 4.1.1 on 2022-12-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoTalleres', '0003_login_delete_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='tipo',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
